### ISSUE TITLE
Smoother image loading UI

### ISSUE THREAD

**Issue by breadadams** [microlinkhq/microlinkjs#28]
When the image loads, on slow connections you see it load chunk by chunk. We should wait until the image has loaded before rendering it

**Comment by Kikobeats** [comment]
Inspiration: https://codepen.io/derekmorash/pen/NjBvdX

**Comment by breadadams** [comment]
Nice @Kikobeats, however that effect _works_ thanks to the availability of low-res images (100x100), whilst the larger images load. Does the API expose anything like this?

Also got to add, [The Beautiful Game](https://vulfpeck.bandcamp.com/album/the-beautiful-game) is an **awesome** album.
