### ISSUE TITLE
Review hover style

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/microlinkjs#31]
- Probably it should be disabled if the card content is loading?
- On facebook, when you hover a card just change the box shadow (a bit). On the other hand, on Twitter, it changes the border color.

**Comment by breadadams** [comment]
> Probably it should be disabled if the card content is loading?

Yeah I thought the same, valid points @kikobeats

**Comment by breadadams** [comment]
I also think we should adjust the hover animation in general, the opacity transition is **way** too harsh atm
