### ISSUE TITLE
Add update deps as pretest step

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/microlinkjs#42]
Because [greenkper doesn't support monorepo](https://greenkeeper.io/docs.html), we need a way to maintain deps up to date.

maintain deps is boring; this is why devDependencies are locked as `latest`, but for `dependencies` we need a less aggresive strategy.

I'm thinking in use [ncu](https://github.com/tjunnone/npm-check-updates) as a `pretest` step

Just need to exit with a code error when deps are available.

Ideally, we can extrac this as build status using https://github.com/siddharthkp/github-build

**Comment by breadadams** [comment]
I'm not sure I fully understand your theory @Kikobeats, you mean:

- We add `npm-check-updates` in build process
- On build, check if there are updates
- If there are updates exit with a code error?

Last step is what I don't get. And what versions would we _set_ in `package.json`?
