### ISSUE TITLE
[Request] Provide other module types

### ISSUE THREAD

**Issue by HamedFathi** [microlinkhq/microlinkjs#47]
Hi

Thanks for your efforts.

please provide other module types too especially `commonjs`.
We work on with [FuseBox](https://github.com/fuse-box/fuse-box) so we need `commonjs` type.

Please provide

- **commonjs**
- amd
- esnext

Thanks :D

**Comment by Kikobeats** [comment]
Probably using something like microbundle but currently looks very alpha https://github.com/developit/microbundle

**Comment by HamedFathi** [comment]
@Kikobeats 

We don't want to change our bundler, we need to support other types in your library.
like [PasswordMeter](https://github.com/HamedFathi/PasswordMeter/tree/master/dist)

I support four common types in PasswordMeter.

**Comment by Kikobeats** [comment]
Yes, my comment was oriented to myself in how to update the microlinkjs bundle process for support more bundle types.

How do you do that at PasswordMeter?

**Comment by HamedFathi** [comment]
My library is based on Typescript so I use a simple gulp task for this purpose
[Gulp Task](https://github.com/HamedFathi/PasswordMeter/blob/master/gulpfile.js)

**Comment by Kikobeats** [comment]
Will be shipped at `1.2.0` soon :D

**Comment by Kikobeats** [comment]
Hey @HamedFathi, can you help me if the new `commonjs` that I'm preparing is working fine?

I created it using [commonjs2 target from webpack](https://webpack.js.org/configuration/output/#module-definition-systems)

It should be works loading the following script:
https://rawgit.com/microlinkhq/microlinkjs/master/packages/microlinkjs/commonjs/microlink.js

Waiting your response!

**Comment by HamedFathi** [comment]
@Kikobeats,
Hi
You are Rock!
I created a **custom element** with your new library (`commonjs`) in [Aurelia](http://aurelia.io/) and it works **perfectly**.

![untitled](https://user-images.githubusercontent.com/8418700/34175230-ff83954e-e510-11e7-8abc-81cd4adb900e.png)

**Comment by Kikobeats** [comment]
Thanks for the feedback! I'm going to release the new version right now 😄
