### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by 4044ever** [microlinkhq/microlinkjs#56]
Page: https://github.com/microlinkhq/microlinkjs

The API link in "See **API** for know what option you can pass. is dead. 

The given inline example also doesn't work, tried:

`<script type="text/javascript" src="https://unpkg.com/microlinkjs@1.2.5/src/index.js"></script>`
`<a class="link" data-round="true" href="http://microlink.js.org">microlink.js.org</a>`

Works like normal href link and only _microlink.js.org_ is displayed.

A complete example would be great to the lesser-coders ;-) I mean the next step after the json return.

Would love to get compact links as on https://microlink-storybook.netlify.com

**Comment by Kikobeats** [comment]
Hey,

Sorry for the vague documentation. We are creating a new fresh documentation site.

About your problem, actually you need to do two steps:

1. Link the microlink JavaScript script in your index.html before close body tag:

```html
<script type="text/javascript" src="//unpkg.com/microlinkjs@latest/umd/microlink.min.js"></script>
```

This will add `window.microlink` as a global object. Check if it exists!

2. After this script, declare a script specifing what HTML tags you want to see as microlink cards:

```html
<script>
// Replace links after DOMContentLoaded
document.addEventListener('DOMContentLoaded', function (event) {
  microlink('a', { round: true })
})
</script>
```

**Comment by 4044ever** [comment]
Ok, the microlink JavaScript script can not be in the HEAD. Works fine inside the BODY.

Coming to the next problem, now ALL links have preview. I use Wordpress, so all HOME, MENU, THEME links are with 'preview'. Is there a way to just use preview on specific links?

**Comment by Kikobeats** [comment]
You need to use a specific selector for that.

If you use `a` selector, like

```
microlink('a', { round: true })
```

yeah, all links will be showed as card.

The approach for just select a set of selector is use a specific class name:

```
microlink('.link-preview', { round: true })
```

Then, add `link-preview` class into your `a` elements to show them as cards.

PS: Please, continue commenting. I need to debug the user board process and all of this feedback help us build better documentation site 🙏

**Comment by breadadams** [comment]
Also on a sidenote @4044ever, we're working on a WP integration. So essentially you'd be able to include Microlink easily, and convert links to cards with simple `[shortcodes /]`.

**Comment by 4044ever** [comment]
Here is what I tried now, and looks like it works perfectly:

`<script type="text/javascript" src="//unpkg.com/microlinkjs@latest/umd/microlink.min.js"></script>

<script>
// Replace links after DOMContentLoaded
document.addEventListener('DOMContentLoaded', function (event) {
  microlink('.mcl', { round: true })
})
</script>

<a class="mcl" href='https://nike'>NIKE</a>`

**Comment by Kikobeats** [comment]
@4044ever 

If you exceeded the daily quota, simply the links looks all time loading; also the dev tools console will be output an error saying you need to upgrade

**Comment by Kikobeats** [comment]
new documentation site is live at http://docs.microlink.io 🎉
