### ISSUE TITLE
[Request] Add custom content

### ISSUE THREAD

**Issue by HamedFathi** [microlinkhq/microlinkjs#65]
Can I add custom content to the microlink.js? more text, link,...

**Comment by Kikobeats** [comment]
Can you put an example? I don't understand your vision

**Comment by HamedFathi** [comment]
We are working on [AureliaToolbet](https://aurelia-toolbelt.github.io). A collection of rich UI based on Bootstrap 4 for [Aurelia](http://aurelia.io/)

See this sample please [abt-password](https://aurelia-toolbelt.github.io/#/bootstrap/password)

as you see I used your `microlink` as Aurelia component but I want to put `License : MIT` into block as extra content of `microlink`.

Do you get my point? Is it possible? of course, I can inject my data based on your class names but I want to know Is there a specific way or not?

![image](https://user-images.githubusercontent.com/8418700/35798471-1ef9fa62-0a78-11e8-8131-96facc36e92e.png)

**Comment by Kikobeats** [comment]
This case of use is very particular to be supported from the microlinkjs side.

I suppose you can do it manipulating the dom and insert a new child element in the microlink subtreee.

**Comment by breadadams** [comment]
You're in luck @HamedFathi, #69 will land _soon_ 😉
