### ISSUE TITLE
Play/Pause button overlay

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/microlinkjs#67]
![screen shot 2018-02-10 at 16 30 36](https://user-images.githubusercontent.com/2096101/36063638-d93e4fc6-0e7f-11e8-8ff5-636d4cce99bf.png)

Inspiration:

- [instagram](https://www.instagram.com/p/BXHj-DllyYU/).
- [twitter](https://twitter.com/verge/status/957383241714970624).

**Comment by breadadams** [comment]
I like the insta. approach, very minimalist 👨‍🎨
