### ISSUE TITLE
CardMedia align to right

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/microlinkjs#70]
```
Flex-direction: row-reverse
```

![](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B6Okdz75tqQsM3ZqMmJXdjRyZk0/components-cards9.png)

**Comment by breadadams** [comment]
What would you suggest for the API here @Kikobeats?

1. `alignMedia`, receives `left` (default)  or `right`. (cons, we'd need top/bottom for large card)
2. `rightAlignMedia`, `true` or `false` (default)
3. Drop this feature and use `flex-direction: row-reverse` (or `flex-direction: column-reverse` on large cards) via the `style` prop to achieve the look? (pros, no need for new API rule, like what we decided on recently with the `mediaSize` prop https://github.com/microlinkhq/microlinkjs/pull/63/commits/76f2731c21aeda693375a61637d85f2426327713)
4. `reverse`, `true` or `false` (default). (pros, naming _works_ for all sizes)

![image](https://user-images.githubusercontent.com/5795227/36433294-745f4850-165c-11e8-9858-d25dece73ce3.png)

**Comment by Kikobeats** [comment]
good points!

I think `reverse` is the best option because `right|left` doesn't make sense for large card
