### ISSUE TITLE
Better container wrapper

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/microlinkjs#93]
Playing with https://microlinkhq.github.io/gallery/sumacrm/

The only way to see the card centered is creating a wrapper around the target `a` element:

```
<div class="link-container">
  <a href="https://www.sumacrm.com/" target="_blank" class="link-preview" data-image="logo"></a>
</div>
```

This adds a bit of friction between the user and the library.

On the other side, using the library on my [blog](https://kikobeats.com/naming-things/) I was to add a minimal CSS to ensure card visualization is ok.

```
.layout-post .card-preview {
  text-decoration: none;
  display: block;
  max-width: 500px;
  margin: auto;
}
```

We need to explore a way to avoid user do that

**Comment by breadadams** [comment]
A simpler way of centring the card, fyi @Kikobeats 

```html
<div style="text-align:center">
  <a ... style="display:inline-block" />
</div>
```

Although the `text-align:left` reset is needed on the text strings for this 💡

**Comment by Kikobeats** [comment]
I made a little change and the sumacrm example looks fine now:
https://github.com/microlinkhq/gallery/commit/5b3b8de4bbcf2701494a41e088c62cd2539ad827

I need to experiment with more websites, probably it could be too dependent of the HTML markup of each website
